[tool.poetry]
name = "angular20-minimal-backend"
version = "0.1.0"
description = "Minimal Poetry project to test frogbot multi-tech scan"
authors = ["test <test@test.com>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "2.28.0"
flask = "2.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
